#!/bin/bash
#------------------------------------------------------------------------------

n=(0 147 294 441 588 735 882)
naca1=(0 1 2 3 4 5 6)
range=(0 1 2 3 4 5 6)
for k in ${range[@]}
do
	cp autoSingle_woO_random autoSingle_woO_random${k}
	sed -i "s/firstnum/${naca1[$k]}/g" autoSingle_woO_random${k}
	sed -i "s/nnumber/${n[$k]}/g" autoSingle_woO_random${k}
	nohup ./autoSingle_woO_random${k} > log.random${k} 2>&1 &
done
